masternode:
    image: kunstmaan/multichain:master
    expose:
        - "7447"
    ports:
        - "8000"

slavenode1:
    image: kunstmaan/multichain:node
    links:
        - masternode

slavenode2:
    image: kunstmaan/multichain:node
    links:
        - masternode
